import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-pregnancy-form',
  templateUrl: './pregnancy-form.component.html',
  styleUrls: ['./pregnancy-form.component.scss']
})
export class PregnancyFormComponent implements OnInit {

  PregnancyForm: FormGroup;
  submitted = false;
  success = false;

  constructor(private formBuilder: FormBuilder) { }

  ngOnInit() {

    this.PregnancyForm = this.formBuilder.group({

     maiden_or_risked:[''],
     blood_group: ['',Validators.required],
     identified_maternal_risks_diseases: [''],
     //registration_details
		registration_number: ['',Validators.required],
		registration_date: ['',Validators.required],
		registered_place: ['',Validators.required],
		registered_date_according_to_the_approved_family_document: ['',Validators.required],
		grama_niladari_division: ['',Validators.required],
		phm_devision: ['',Validators.required],
		phi_devision: ['',Validators.required],
		//mother details
    // mother_id:['',Validators.required],
    mothers_name:['',Validators.required],
    mothers_age:['',Validators.required],
    husband_name:[''],
    husband_age:[''],
    mothers_education_level:[''],
    husbands_education_level:[''],
    mothers_occupation:[''],
    fathers_occupation:[''],
    address: [''],
		telephone: [''],
		distance_to_mothers_workplace : [''],
    mothers_age_at_marriage: [''],
    
    blood_relatives_marriage: [''],
    injected_for_rubella: [''],
    done_pre_pregnancy_test: [''],
    is_forlic_acid_given: [''],
    history_of_madasarubawaya: [''],
    //pregnancy_history_current_pregnancy_status
    which_pregnancy: [''],
    no_of_living_children: [''],
    age_of_the_youngest_child:[''],
    last_menstrual_date:[''],
    expected_dilivery_date:[''],
    expected_dilivery_date_corrected_by_US:[''],
    expecting_time_period:[''],
    weeks_into_pregnancy_when_registration: [''],
    have_used_any_family_organization_method: [''],
    //current status
    between_20t025_ages_yesORno:[''],
    between_20t025_ages_details:[''],
    fifth_pregnanycy_or_yesORno:[''],
    fifth_pregnanycy_or_details:[''],
    uterine_diseaces_or_high_blood_sugar_yesORno:[''],
    uterine_diseaces_or_high_blood_sugar_details:[''],
    prenatal_vaginal_bleeding_yesORno:[''],
    prenatal_vaginal_bleeding_details:[''],
    abnormal_positioning_yesORno:[''],
    abnormal_positioning_details:[''],
    not_knowing_the_exact_delivery_date_yesORno:[''],
    not_knowing_the_exact_delivery_date_details:[''],
    other_yesORno:[''],
    other_details:[''],
    // other_risky_situations
		bmi_below20_or_above25_yesORno: [''],
		bmi_below20_or_above25_details: [''],
		diabetes_yesORno: [''],
		diabetes_details: [''],
		malaria_yesORno: [''],
		malaria_details: [''],
		heart_problems_yesORno: [''],
	 	heart_problems_details: [''],
    other_risky_yesORno:[''],
    other_risky_details:[''],
  //Previous Pregnancy Detials
    g1_result: [''],
    g1_delivery_details: [''],
    g1_delivered_place: [''],
    g1_bron_weight: [''],
    g1_delivery_abnormalities: [''],
    g1_sex: [''],
    g2_result: [''],
    g2_delivery_details: [''],
    g2_delivered_place: [''],
    g2_bron_weight: [''],
    g2_delivery_abnormalities: [''],
    g2_sex: [''],
    g3_result: [''],
    g3_delivery_details: [''],
    g3_delivered_place: [''],
    g3_bron_weight: [''],
    g3_delivery_abnormalities: [''],
    g3_sex: [''],
    g4_result: [''],
    g4_delivery_details: [''],
    g4_delivered_place: [''],
    g4_bron_weight: [''],
    g4_delivery_abnormalities: [''],
    g4_sex: [''],
    g5_result: [''],
    g5_delivery_details: [''],
    g5_delivered_place: [''],
    g5_bron_weight: [''],
    g5_delivery_abnormalities: [''],
    g5_sex: [''],
   //family_diseases_details
    diabetes_history_status:[''],
    diabetes_history_details: [''],
    high_blood_preasre_history_status:[''],
    high_blood_preasre_history_details: [''],
    blood_diseases_history_status:[''],
    blood_diseases_history_details: [''],
    other_history_status:[''],
    other_history_details: [''],

   //early_obstetric_details
    day1_date:[''],
    day1_pregnancy_weeks:[''],
    day1_urine:[''],
    day1_natritional_needs_myths:[''],
    day1_embryo_height:[''],
    day1_embryo_moves:[''],
    day1_embryo_sounds:[''],
    day1_informed_delivery_time:[''],
    day1_is_it_informed:[''],
    
    day2_date:[''],
    day2_pregnancy_weeks:[''],
    day2_urine:[''],
    day2_natritional_needs_myths:[''],
    day2_embryo_height:[''],
    day2_embryo_moves:[''],
    day2_embryo_sounds:[''],
    day2_informed_delivery_time:[''],
    day2_is_it_informed:[''],
    
    day3_date:[''],
    day3_pregnancy_weeks:[''],
    day3_urine:[''],
    day3_natritional_needs_myths:[''],
    day3_embryo_height:[''],
    day3_embryo_moves:[''],
    day3_embryo_sounds:[''],
    day3_informed_delivery_time:[''],
    day3_is_it_informed:[''],
   
    day4_date:[''],
    day4_pregnancy_weeks:[''],
    day4_urine:[''],
    day4_natritional_needs_myths:[''],
    day4_embryo_height:[''],
    day4_embryo_moves:[''],
    day4_embryo_sounds:[''],
    day4_informed_delivery_time:[''],
    day4_is_it_informed:[''],
   
    //	other
    temporiry_left_the_province:[''],
    is_it_informed:[''],
    in_delivery_hospital: [''],
	  in_delivery_transport_method: [''],
    in_an_emergency_hospital: [''],
    in_an_emergency_transport_method: [''],

    //clinic Details
    day1_clinical_day: [''],
    day1_weeks_into_pregnancy: [''],
    day1_weight: [''],
    day1_urine_sugar: [''],
    day1_urine_hemoglobin: [''],
    day1_blood_pressure: [''],
    day1_position: [''],
    day1_embry_moves: [''],
    day1_embry_sounds: [''],
    day1_iron_folate: [''],
    day1_vitamin_c: [''],
    day1_calsium_malaria_treatments: [''],
    day1_threeposha: [''],
    day1_checked_by: [''],

    day2_clinical_day: [''],
    day2_weeks_into_pregnancy: [''],
    day2_weight: [''],
    day2_urine_sugar: [''],
    day2_urine_hemoglobin: [''],
    day2_blood_pressure: [''],
    day2_position: [''],
    day2_embry_moves: [''],
    day2_embry_sounds: [''],
    day2_iron_folate: [''],
    day2_vitamin_c: [''],
    day2_calsium_malaria_treatments: [''],
    day2_threeposha: [''],
    day2_checked_by: [''],

    day3_clinical_day: [''],
    day3_weeks_into_pregnancy: [''],
    day3_weight: [''],
    day3_urine_sugar: [''],
    day3_urine_hemoglobin: [''],
    day3_blood_pressure: [''],
    day3_position: [''],
    day3_embry_moves: [''],
    day3_embry_sounds: [''],
    day3_iron_folate: [''],
    day3_vitamin_c: [''],
    day3_calsium_malaria_treatments: [''],
    day3_threeposha: [''],
    day3_checked_by: [''],

    day4_clinical_day: [''],
    day4_weeks_into_pregnancy: [''],
    day4_weight: [''],
    day4_urine_sugar: [''],
    day4_urine_hemoglobin: [''],
    day4_blood_pressure: [''],
    day4_position: [''],
    day4_embry_moves: [''],
    day4_embry_sounds: [''],
    day4_iron_folate: [''],
    day4_vitamin_c: [''],
    day4_calsium_malaria_treatments: [''],
    day4_threeposha: [''],
    day4_checked_by: [''],

    day5_clinical_day: [''],
    day5_weeks_into_pregnancy: [''],
    day5_weight: [''],
    day5_urine_sugar:[''],
    day5_urine_hemoglobin:[''],
    day5_blood_pressure:[''],
    day5_position: [''],
    day5_embry_moves: [''],
    day5_embry_sounds: [''],
    day5_iron_folate: [''],
    day5_vitamin_c: [''],
    day5_calsium_malaria_treatments: [''],
    day5_threeposha: [''],
    day5_checked_by: [''],

    day6_clinical_day: [''],
    day6_weeks_into_pregnancy: [''],
    day6_weight: [''],
    day6_urine_sugar:[''],
    day6_urine_hemoglobin:[''],
    day6_blood_pressure:[''],
    day6_position: [''],
    day6_embry_moves: [''],
    day6_embry_sounds: [''],
    day6_iron_folate: [''],
    day6_vitamin_c: [''],
    day6_calsium_malaria_treatments: [''],
    day6_threeposha: [''],
    day6_checked_by: [''],

    day7_clinical_day: [''],
    day7_weeks_into_pregnancy: [''],
    day7_weight: [''],
    day7_urine_sugar:[''],
    day7_urine_hemoglobin:[''],
    day7_blood_pressure:[''],
    day7_position: [''],
    day7_embry_moves: [''],
    day7_embry_sounds: [''],
    day7_iron_folate: [''],
    day7_vitamin_c: [''],
    day7_calsium_malaria_treatments: [''],
    day7_threeposha: [''],
    day7_checked_by: [''],

    day8_clinical_day: [''],
    day8_weeks_into_pregnancy: [''],
    day8_weight: [''],
    day8_urine_sugar:[''],
    day8_urine_hemoglobin:[''],
    day8_blood_pressure:[''],
    day8_position: [''],
    day8_embry_moves: [''],
    day8_embry_sounds: [''],
    day8_iron_folate: [''],
    day8_vitamin_c: [''],
    day8_calsium_malaria_treatments: [''],
    day8_threeposha: [''],
    day8_checked_by: [''],

    //other medical details
    date_of_issued_embry_moves_form:[''],
    worm_treatment_given_date: [''],
    tetanus_treatments_type: [''],
    tetanus_treatments_given_date: [''],
    tetanus_treatments_type_number: [''],

    height: [''],
		bmi: [''],
		vdrl_blood_sample_obtained_date: [''],
		vdrl_weeks_into_pregnancy_when_blood_sample_was_obtained: [''],
		vdrl_date_of_results: [''],
		vdrl_result: [''],
		vdrl_date_of_referral_for_further_treatments: [''],
		was_blood_sample_taken_fot_pretest_for_hiv: [''],
		was_blood_sample_taken_fot_pretest_for_malaria: [''],
		breast_test: [''],
		cardiac_examination_first_three_month: [''],
		cardiac_examination_second_three_month: [''],
		cardiac_examination_third_three_month: [''],
	   lungs: [''],
		dental_test: [''],
    dental_caries: [''],
    blood_sugar_week:[''],
		blood_sugar_result:[''],
		hemoglobin_week:[''],
		hemoglobin_result:[''],
		malaria_week:[''],
		malaria_result:[''],
		participating_clinics: [''],
      
  //after delivery
    vitamin_c_overdose: [''],
    rubella_date: [''],
    rubella_type: [''],
    day_mother_came_home: [''],
    child_sex: [''],
    child_birth_weight: [''],
    child_immatured: [''],
    child_abnormalities: [''],
    child_other_details: [''],
    unidentified_abnormalities:[''],

    maternal_deathsdate: [''],
		maternal_deathsreason: [''],
    maternal_deathsinversigated: [''],
    
    //post travel days
		day1travel_date: [''],
		day1mother_temperature: [''],
		day1mother_paleness: [''],
		day1mother_breast: [''],
		day1mother_filamemtous_blood: [''],
		day1mother_mental_changes: [''],
		day1mother_diarrrhea: [''],
		day1mother_vomiting: [''],
		day1mother_breathing_difficulties: [''],
		day1mother_visual_difficulties: [''],
		day1mother_pain_in_kent: [''],
		day1mother_prebiotics: [''],
		day1child_abnormalities: [''],
		day1child_fever: [''],
		day1child_skin_color: [''],
		day1child_infections_near_umbilicus: [''],
		day1child_suckling: [''],
		day1child_prebiotics: [''],

		day2travel_date: [''],
		day2mother_temperature: [''],
		day2mother_paleness: [''],
		day2mother_breast: [''],
		day2mother_filamemtous_blood: [''],
		day2mother_mental_changes: [''],
		day2mother_diarrrhea: [''],
		day2mother_vomiting: [''],
		day2mother_breathing_difficulties: [''],
		day2mother_visual_difficulties: [''],
		day2mother_pain_in_kent: [''],
		day2mother_prebiotics: [''],
		day2child_abnormalities: [''],
		day2child_fever: [''],
		day2child_skin_color: [''],
		day2child_infections_near_umbilicus: [''],
		day2child_suckling: [''],
		day2child_prebiotics: [''],

		day3travel_date: [''],
		day3mother_temperature: [''],
		day3mother_paleness: [''],
		day3mother_breast: [''],
		day3mother_filamemtous_blood: [''],
		day3mother_mental_changes: [''],
		day3mother_diarrrhea: [''],
		day3mother_vomiting: [''],
		day3mother_breathing_difficulties: [''],
		day3mother_visual_difficulties: [''],
		day3mother_pain_in_kent: [''],
		day3mother_prebiotics: [''],
		day3child_abnormalities: [''],
		day3child_fever: [''],
		day3child_skin_color: [''],
		day3child_infections_near_umbilicus: [''],
		day3child_suckling: [''],
		day3child_prebiotics: [''],

		day4travel_date: [''],
		day4mother_temperature: [''],
		day4mother_paleness: [''],
		day4mother_breast: [''],
		day4mother_filamemtous_blood: [''],
		day4mother_mental_changes: [''],
		day4mother_diarrrhea: [''],
		day4mother_vomiting: [''],
		day4mother_breathing_difficulties: [''],
		day4mother_visual_difficulties: [''],
		day4mother_pain_in_kent: [''],
		day4mother_prebiotics: [''],
		day4child_abnormalities: [''],
		day4child_fever: [''],
		day4child_skin_color: [''],
		day4child_infections_near_umbilicus: [''],
		day4child_suckling: [''],
    day4child_prebiotics: [''],
    
    day5travel_date: [''],
		day5mother_temperature: [''],
		day5mother_paleness: [''],
		day5mother_breast: [''],
		day5mother_filamemtous_blood: [''],
		day5mother_mental_changes: [''],
		day5mother_diarrrhea: [''],
		day5mother_vomiting: [''],
		day5mother_breathing_difficulties: [''],
		day5mother_visual_difficulties: [''],
		day5mother_pain_in_kent: [''],
		day5mother_prebiotics: [''],
		day5child_abnormalities: [''],
		day5child_fever: [''],
		day5child_skin_color: [''],
		day5child_infections_near_umbilicus: [''],
		day5child_suckling: [''],
		day5child_prebiotics: [''],

		day6travel_date: [''],
		day6mother_temperature: [''],
		day6mother_paleness: [''],
		day6mother_breast: [''],
		day6mother_filamemtous_blood: [''],
		day6mother_mental_changes: [''],
		day6mother_diarrrhea: [''],
		day6mother_vomiting: [''],
		day6mother_breathing_difficulties: [''],
		day6mother_visual_difficulties: [''],
		day6mother_pain_in_kent: [''],
		day6mother_prebiotics: [''],
		day6child_abnormalities: [''],
		day6child_fever: [''],
		day6child_skin_color: [''],
		day6child_infections_near_umbilicus: [''],
		day6child_suckling: [''],
		day6child_prebiotics: [''],

		day7travel_date: [''],
		day7mother_temperature: [''],
		day7mother_paleness: [''],
		day7mother_breast: [''],
		day7mother_filamemtous_blood: [''],
		day7mother_mental_changes: [''],
		day7mother_diarrrhea: [''],
		day7mother_vomiting: [''],
		day7mother_breathing_difficulties: [''],
		day7mother_visual_difficulties: [''],
		day7mother_pain_in_kent: [''],
		day7mother_prebiotics: [''],
		day7child_abnormalities: [''],
		day7child_fever: [''],
		day7child_skin_color: [''],
		day7child_infections_near_umbilicus: [''],
		day7child_suckling: [''],
		day7child_prebiotics: [''],

		day8travel_date: [''],
		day8mother_temperature: [''],
		day8mother_paleness: [''],
		day8mother_breast: [''],
		day8mother_filamemtous_blood: [''],
		day8mother_mental_changes: [''],
		day8mother_diarrrhea: [''],
		day8mother_vomiting: [''],
		day8mother_breathing_difficulties: [''],
		day8mother_visual_difficulties: [''],
		day8mother_pain_in_kent: [''],
		day8mother_prebiotics: [''],
		day8child_abnormalities: [''],
		day8child_fever: [''],
		day8child_skin_color: [''],
		day8child_infections_near_umbilicus: [''],
		day8child_suckling: [''],
    day8child_prebiotics: [''],
    
    
    others_details:[''],
    mental_health_according_to_edingburo: [''],
		new_born_baby_bcg: [''],
		new_born_baby_if_died_when: [''],
		new_born_baby_if_died_reason: [''],
		new_born_baby_if_died_inversigated: [''],
		does_mother_comes_to_post_delivery_clinics: [''],
    accepted_family_organization_method: [''],
    why_accepted_family_organization_method: ['']



	  
		


    })
  }

  onSubmit() {
    this.submitted = true;
      

    if (this.PregnancyForm.invalid) {
        return;
    }

    this.success = true;
  }

}
