import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import '../globals.dart' as globals;

Future<Baby> fetchBaby() async {
  print('fetch Baby function');
  //String _babyId = globals.BabyId + babyIndex;
  final response = await http.get(
      'https://protected-bayou-52277.herokuapp.com/babies/viewbyid/${globals.babyId}');
  print('status code');
  print(response.statusCode);
  print(response.body);
  // final json = jsonDecode(response.body);
  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON.
    //return (json.decode(response.body));
    //print(Baby.fromJson(json.decode(response.body)));
    return Baby.fromJson(json.decode(response.body)[0]);
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load Baby');
  }
}

class Baby {
  final String title,
      date1mo,
      eye1mo,
      squint1mo,
      cataract1mo,
      hearingL1mo,
      hearingR1mo,
      weight1mo,
      height1mo,
      development,
      heart1mo,
      lungs1mo,
      hipJoint1mo,
      inhProblems1mo,
      otherDiseases1mo,
      dentalSpots,
      officer1mo,

      ///
      date2mo,
      eye2mo,
      squint2mo,
      cataract2mo,
      hearingL2mo,
      hearingR2mo,
      weight2mo,
      height2mo,
      //development,
      heart2mo,
      lungs2mo,
      hipJoint2mo,
      inhProblems2mo,
      otherDiseases2mo,
      officer2mo,

      ///

      date4mo,
      eye4mo,
      squint4mo,
      cataract4mo,
      hearingL4mo,
      hearingR4mo,
      weight4mo,
      height4mo,
      //development,
      heart4mo,
      lungs4mo,
      hipJoint4mo,
      inhProblems4mo,
      otherDiseases4mo,
      officer4mo,

      ///
      date6mo,
      eye6mo,
      squint6mo,
      cataract6mo,
      hearingL6mo,
      hearingR6mo,
      weight6mo,
      height6mo,
      //development,
      heart6mo,
      lungs6mo,
      hipJoint6mo,
      inhProblems6mo,
      otherDiseases6mo,
      dentalSpots6mo,
      dentalCavities6mo,
      officer6mo,

      ///
      date9mo,
      eye9mo,
      squint9mo,
      cataract9mo,
      hearingL9mo,
      hearingR9mo,
      weight9mo,
      height9mo,
      //development,
      heart9mo,
      lungs9mo,
      hipJoint9mo,
      inhProblems9mo,
      otherDiseases9mo,
      officer9mo,
      dentalSpots9mo,
      dentalCavities9mo,

      ///
      date12mo,
      eye12mo,
      squint12mo,
      cataract12mo,
      hearingL12mo,
      hearingR12mo,
      weight12mo,
      height12mo,
      //development,
      heart12mo,
      lungs12mo,
      hipJoint12mo,
      inhProblems12mo,
      otherDiseases12mo,
      officer12mo,
      dentalSpots12mo,
      dentalCavities12mo,

      ///
      date18mo,
      eye18mo,
      squint18mo,
      cataract18mo,
      hearingL18mo,
      hearingR18mo,
      weight18mo,
      height18mo,
      //development,
      heart18mo,
      lungs18mo,
      hipJoint18mo,
      inhProblems18mo,
      otherDiseases18mo,
      officer18mo,
      dentalSpots18mo,
      dentalCavities18mo,

      ///

      date3y,
      eye3y,
      squint3y,
      cataract3y,
      hearingL3y,
      hearingR3y,
      weight3y,
      height3y,
      //development,
      heart3y,
      lungs3y,
      hipJoint3y,
      inhProblems3y,
      otherDiseases3y,
      officer3y,
      dentalSpots3y,
      dentalCavities3y,
      nightBlind3y,
      bitoSpots3y,

      ///
      date4y,
      eye4y,
      squint4y,
      cataract4y,
      hearingL4y,
      hearingR4y,
      weight4y,
      height4y,
      //development,
      heart4y,
      lungs4y,
      hipJoint4y,
      inhProblems4y,
      otherDiseases4y,
      officer4y,
      dentalSpots4y,
      dentalCavities4y,
      nightBlind4y,
      bitoSpots4y,

      
      date5y,
      eye5y,
      squint5y,
      cataract5y,
      hearingL5y,
      hearingR5y,
      weight5y,
      height5y,
      //development,
      heart5y,
      lungs5y,
      hipJoint5y,
      inhProblems5y,
      otherDiseases5y,
      officer5y,
      dentalSpots5y,
      dentalCavities5y,
      nightBlind5y,
      bitoSpots5y,
      sightL5y,
      sightR5y;
  // officer1mo,
  // dentalSpots,
  // officer1mo,
  // dentalSpots,
  // officer1mo,

  // deantalCavities,

  Baby(
      {this.title,
      this.date1mo,
      this.eye1mo,
      this.squint1mo,
      this.cataract1mo,
      this.hearingL1mo,
      this.hearingR1mo,
      this.weight1mo,
      this.height1mo,
      this.development,
      this.heart1mo,
      this.lungs1mo,
      this.hipJoint1mo,
      this.inhProblems1mo,
      this.otherDiseases1mo,
      this.dentalSpots,
      this.officer1mo,
      this.date2mo,
      this.eye2mo,
      this.squint2mo,
      this.cataract2mo,
      this.hearingL2mo,
      this.hearingR2mo,
      this.weight2mo,
      this.height2mo,
      this.heart2mo,
      this.lungs2mo,
      this.hipJoint2mo,
      this.inhProblems2mo,
      this.otherDiseases2mo,
      this.officer2mo,
      this.date4mo,
      this.eye4mo,
      this.squint4mo,
      this.cataract4mo,
      this.hearingL4mo,
      this.hearingR4mo,
      this.weight4mo,
      this.height4mo,
      this.heart4mo,
      this.lungs4mo,
      this.hipJoint4mo,
      this.inhProblems4mo,
      this.otherDiseases4mo,
      this.officer4mo,
      this.date6mo,
      this.eye6mo,
      this.squint6mo,
      this.cataract6mo,
      this.hearingL6mo,
      this.hearingR6mo,
      this.weight6mo,
      this.height6mo,
      this.heart6mo,
      this.lungs6mo,
      this.hipJoint6mo,
      this.inhProblems6mo,
      this.otherDiseases6mo,
      this.dentalSpots6mo,
      this.dentalCavities6mo,
      this.officer6mo,
      this.date9mo,
      this.eye9mo,
      this.squint9mo,
      this.cataract9mo,
      this.hearingL9mo,
      this.hearingR9mo,
      this.weight9mo,
      this.height9mo,
      this.heart9mo,
      this.lungs9mo,
      this.hipJoint9mo,
      this.inhProblems9mo,
      this.otherDiseases9mo,
      this.officer9mo,
      this.dentalSpots9mo,
      this.dentalCavities9mo,
      this.date12mo,
      this.eye12mo,
      this.squint12mo,
      this.cataract12mo,
      this.hearingL12mo,
      this.hearingR12mo,
      this.weight12mo,
      this.height12mo,
      this.heart12mo,
      this.lungs12mo,
      this.hipJoint12mo,
      this.inhProblems12mo,
      this.otherDiseases12mo,
      this.officer12mo,
      this.dentalSpots12mo,
      this.dentalCavities12mo,
      this.date18mo,
      this.eye18mo,
      this.squint18mo,
      this.cataract18mo,
      this.hearingL18mo,
      this.hearingR18mo,
      this.weight18mo,
      this.height18mo,
      this.heart18mo,
      this.lungs18mo,
      this.hipJoint18mo,
      this.inhProblems18mo,
      this.otherDiseases18mo,
      this.officer18mo,
      this.dentalSpots18mo,
      this.dentalCavities18mo,
      this.date3y,
      this.eye3y,
      this.squint3y,
      this.cataract3y,
      this.hearingL3y,
      this.hearingR3y,
      this.weight3y,
      this.height3y,
      this.heart3y,
      this.lungs3y,
      this.hipJoint3y,
      this.inhProblems3y,
      this.otherDiseases3y,
      this.officer3y,
      this.dentalSpots3y,
      this.dentalCavities3y,
      this.nightBlind3y,
      this.bitoSpots3y,
      this.date4y,
      this.eye4y,
      this.squint4y,
      this.cataract4y,
      this.hearingL4y,
      this.hearingR4y,
      this.weight4y,
      this.height4y,
      this.heart4y,
      this.lungs4y,
      this.hipJoint4y,
      this.inhProblems4y,
      this.otherDiseases4y,
      this.officer4y,
      this.dentalSpots4y,
      this.dentalCavities4y,
      this.nightBlind4y,
      this.bitoSpots4y,
      this.date5y,
      this.eye5y,
      this.squint5y,
      this.cataract5y,
      this.hearingL5y,
      this.hearingR5y,
      this.weight5y,
      this.height5y,
      this.heart5y,
      this.lungs5y,
      this.hipJoint5y,
      this.inhProblems5y,
      this.otherDiseases5y,
      this.officer5y,
      this.dentalSpots5y,
      this.dentalCavities5y,
      this.nightBlind5y,
      this.bitoSpots5y,
      this.sightL5y,
      this.sightR5y});

  factory Baby.fromJson(Map<String, dynamic> json) {
    return Baby(
      // // idNumber: json['Identity_number'],
      // vilID: json['village_id'],
      // wifeName: json['Name_of_wife'],
      // husbandName: json['Name_of_husband'],
      // childrenCount: json['Number_of_living_childern']

      date1mo: json["one_month_date_of_clinics"],
      eye1mo: json["one_month_change_of_eye_size"],
      squint1mo: json["one_month_squint"],
      cataract1mo: json["one_month_cataract"],
      //:json["one_month_impairment_of_eye_movement"],
      hearingL1mo: json["one_month_hearing_left"],
      hearingR1mo: json["one_month_hearing_right"],
      weight1mo: json["one_month_development_weight"],
      height1mo: json["one_month_development_height"],
      heart1mo: json["one_month_heart_disease"],
      lungs1mo: json["one_month_lungs"],
      hipJoint1mo: json["one_month_hip_joint"],
      inhProblems1mo: json["one_month_inheited_problems"],
      otherDiseases1mo: json["one_month_other_diseases"],
      officer1mo: json["one_month_designation_of_officer"],

      date2mo: json["two_month_date_of_clinics"],
      eye2mo: json["two_month_change_of_eye_size"],
      squint2mo: json["two_month_squint"],
      cataract2mo: json["two_month_cataract"],
      //:json["two_month_impairment_of_eye_movement"],
      hearingL2mo: json["two_month_hearing_left"],
      hearingR2mo: json["two_month_hearing_right"],
      weight2mo: json["two_month_development_weight"],
      height2mo: json["two_month_development_height"],
      heart2mo: json["two_month_heart_disease"],
      lungs2mo: json["two_month_lungs"],
      hipJoint2mo: json["two_month_hip_joint"],
      inhProblems2mo: json["two_month_inheited_problems"],
      otherDiseases2mo: json["two_month_other_diseases"],
      officer2mo: json["two_month_designation_of_officer"],

      date4mo: json["four_month_date_of_clinics"],
      eye4mo: json["four_month_change_of_eye_size"],
      squint4mo: json["four_month_squint"],
      cataract4mo: json["four_month_cataract"],
      //:json["four_month_impairment_of_eye_movement"],
      hearingL4mo: json["four_month_hearing_left"],
      hearingR4mo: json["four_month_hearing_right"],
      weight4mo: json["four_month_development_weight"],
      height4mo: json["four_month_development_height"],
      heart4mo: json["four_month_heart_disease"],
      lungs4mo: json["four_month_lungs"],
      hipJoint4mo: json["four_month_hip_joint"],
      inhProblems4mo: json["four_month_inheited_problems"],
      otherDiseases4mo: json["four_month_other_diseases"],
      officer4mo: json["four_month_designation_of_officer"],

      date6mo: json["six_month_date_of_clinics"],
      eye6mo: json["six_month_change_of_eye_size"],
      squint6mo: json["six_month_squint"],
      cataract6mo: json["six_month_cataract"],
      //:json["six_month_impairment_of_eye_movement"],
      hearingL6mo: json["six_month_hearing_left"],
      hearingR6mo: json["six_month_hearing_right"],
      weight6mo: json["six_month_development_weight"],
      height6mo: json["six_month_development_height"],
      heart6mo: json["six_month_heart_disease"],
      lungs6mo: json["six_month_lungs"],
      hipJoint6mo: json["six_month_hip_joint"],
      inhProblems6mo: json["six_month_inheited_problems"],
      otherDiseases6mo: json["six_month_other_diseases"],
      officer6mo: json["six_month_designation_of_officer"],
      dentalSpots6mo: json["six_month_dental_caries_white_brown_spots"],
      dentalCavities6mo: json["six_month_dental_caries_dental_cavities"],

      date9mo: json["nine_month_date_of_clinics"],
      eye9mo: json["nine_month_change_of_eye_size"],
      squint9mo: json["nine_month_squint"],
      cataract9mo: json["nine_month_cataract"],
      //:json["nine_month_impairment_of_eye_movement"],
      hearingL9mo: json["nine_month_hearing_left"],
      hearingR9mo: json["nine_month_hearing_right"],
      weight9mo: json["nine_month_development_weight"],
      height9mo: json["nine_month_development_height"],
      heart9mo: json["nine_month_heart_disease"],
      lungs9mo: json["nine_month_lungs"],
      hipJoint9mo: json["nine_month_hip_joint"],
      inhProblems9mo: json["nine_month_inheited_problems"],
      otherDiseases9mo: json["nine_month_other_diseases"],
      officer9mo: json["nine_month_designation_of_officer"],
      dentalSpots9mo: json["nine_month_dental_caries_white_brown_spots"],
      dentalCavities9mo: json["nine_month_dental_caries_dental_cavities"],

      date12mo: json["twelve_month_date_of_clinics"],
      eye12mo: json["twelve_month_change_of_eye_size"],
      squint12mo: json["twelve_month_squint"],
      cataract12mo: json["twelve_month_cataract"],
      //:json ["twelve_month_impairment_of_eye_movement"],
      hearingL12mo: json["twelve_month_hearing_left"],
      hearingR12mo: json["twelve_month_hearing_right"],
      weight12mo: json["twelve_month_development_weight"],
      height12mo: json["twelve_month_development_height"],
      heart12mo: json["twelve_month_heart_disease"],
      lungs12mo: json["twelve_month_lungs"],
      hipJoint12mo: json["twelve_month_hip_joint"],
      inhProblems12mo: json["twelve_month_inheited_problems"],
      otherDiseases12mo: json["twelve_month_other_diseases"],
      officer12mo: json["twelve_month_designation_of_officer"],
      dentalSpots12mo: json["twelve_month_dental_caries_white_brown_spots"],
      dentalCavities12mo: json["twelve_month_dental_caries_dental_cavities"],

      date18mo: json["eighteen_month_date_of_clinics"],
      eye18mo: json["eighteen_month_change_of_eye_size"],
      squint18mo: json["eighteen_month_squint"],
      cataract18mo: json["eighteen_month_cataract"],
      //:json["eighteen_month_impairment_of_eye_movement"],
      hearingL18mo: json["eighteen_month_hearing_left"],
      hearingR18mo: json["eighteen_month_hearing_right"],
      weight18mo: json["eighteen_month_development_weight"],
      height18mo: json["eighteen_month_development_height"],
      heart18mo: json["eighteen_month_heart_disease"],
      lungs18mo: json["eighteen_month_lungs"],
      hipJoint18mo: json["eighteen_month_hip_joint"],
      inhProblems18mo: json["eighteen_month_inheited_problems"],
      otherDiseases18mo: json["eighteen_month_other_diseases"],
      officer18mo: json["eighteen_month_designation_of_officer"],
      dentalSpots18mo: json["eighteen_month_dental_caries_white_brown_spots"],
      dentalCavities18mo: json["eighteen_month_dental_caries_dental_cavities"],

      date3y: json["three_year_date_of_clinics"],
      eye3y: json["three_year_change_of_eye_size"],
      squint3y: json["three_year_squint"],
      cataract3y: json["three_year_cataract"],
      //:json["three_year_impairment_of_eye_movement"],
      nightBlind3y: json["three_year_night_blindness"],
      bitoSpots3y: json["three_year_bito_spots"],
      hearingL3y: json["three_year_hearing_left"],
      hearingR3y: json["three_year_hearing_right"],
      weight3y: json["three_year_development_weight"],
      height3y: json["three_year_development_height"],
      heart3y: json["three_year_heart_disease"],
      lungs3y: json["three_year_lungs"],
      hipJoint3y: json["three_year_hip_joint"],
      inhProblems3y: json["three_year_inheited_problems"],
      otherDiseases3y: json["three_year_other_diseases"],
      officer3y: json["three_year_designation_of_officer"],
      dentalSpots3y: json["three_year_dental_caries_white_brown_spots"],
      dentalCavities3y: json["three_year_dental_caries_dental_cavities"],

      date4y: json["four_year_date_of_clinics"],
      eye4y: json["four_year_change_of_eye_size"],
      squint4y: json["four_year_squint"],
      cataract4y: json["four_year_cataract"],
      //:json["four_year_impairment_of_eye_movement"],
      nightBlind4y: json["four_year_night_blindness"],
      bitoSpots4y: json["four_year_bito_spots"],
      hearingL4y: json["four_year_hearing_left"],
      hearingR4y: json["four_year_hearing_right"],
      weight4y: json["four_year_development_weight"],
      height4y: json["four_year_development_height"],
      heart4y: json["four_year_heart_disease"],
      lungs4y: json["four_year_lungs"],
      hipJoint4y: json["four_year_hip_joint"],
      inhProblems4y: json["four_year_inheited_problems"],
      otherDiseases4y: json["four_year_other_diseases"],
      officer4y: json["four_year_designation_of_officer"],
      dentalSpots4y: json["four_year_dental_caries_white_brown_spots"],
      dentalCavities4y: json["four_year_dental_caries_dental_cavities"],

      date5y: json["five_year_date_of_clinics"],
      eye5y: json["five_year_change_of_eye_size"],
      squint5y: json["five_year_squint"],
      cataract5y: json["five_year_cataract"],
      //:json ["five_year_impairment_of_eye_movement"],
      sightL5y: json["five_year_sight_left"],
      sightR5y: json["five_year_sight_right"],
      nightBlind5y: json["five_year_night_blindness"],
      bitoSpots5y: json["five_year_bito_spots"],
      hearingL5y: json["five_year_hearing_left"],
      hearingR5y: json["five_year_hearing_right"],
      weight5y: json["five_year_development_weight"],
      height5y: json["five_year_development_height"],
      heart5y: json["five_year_heart_disease"],
      lungs5y: json["five_year_lungs"],
      hipJoint5y: json["five_year_hip_joint"],
      inhProblems5y: json["five_year_inheited_problems"],
      otherDiseases5y: json["five_year_other_diseases"],
      officer5y: json["five_year_designation_of_officer"],
      dentalSpots5y: json["five_year_dental_caries_white_brown_spots"],
      dentalCavities5y: json["five_year_dental_caries_dental_cavities"],
      // childrenCount:
      //     json["total_Number_of_children_alive_including_this_child"].toString(),
    );
  }
}
