const mongoose = require('mongoose');
var Schema = mongoose.Schema;
var baby= new Schema({
    "name_of_child":String,
	"date_of_birth_of_child":{
	     "year":Number,
	     "month":Number,
	     "date":Number
	},
	"date_of_registered":{
	      "year":Number,
	     "month":Number,
	     "date":Number
	},
	"name_of_mother":String,
	"age_of_mother":Number,
	"address":String,
	"total_Number_of_children_alive_including_this_child":Number,
	"method_of_delivery":{
        "normal_delivery":String,
        "low_delivery":String,
        "vacume_dekivery":String,
        "cesarean_surgery":String
	},
	"Number_of_apgas":{
	     "1m":String,
	     "5m":String,
	     "10m":String

	},
	"birth_weight":String,
	"gridle_circumference_at_birth":String,
	"length_of_baby_at_birth":String,
	"weight_in_discharge_from_hospital":String,
	"K_vitamine":Boolean,
	"breast_feeding":{
	    "breast_feeding_during_the_first_hour":Boolean,
	    "unstability":Boolean,
	    "connection":Boolean
	},
	"does_check_congenital_hypothyroidism":Boolean,
	

	"premature_births":{
	   "status":String,
	   "date":Date
	},
	"low_birth_weight":{
	   "status":String,
	   "date":Date
	},
	"neonatal_abnomalities":{
	   "status":String,
	   "date":Date
	},
	"inherited_problems":String,
	"congenital_hypothyroidism":String,
	"server_illness_of_the_mother_after_delivery":{
	   "status":String,
	   "date":Date
	},
	"breastfeeding_at_first_six_months":{
	   "status":String,
	   "date":Date
	},
	"impairments_of_growth":{
	   "status":String,
	   "date":Date
	},
	"death_of_mother_or_father":{
	   "status":String,
	   "date":Date
	},
	"separation_or_depature_of_mother_or_father":{
	   "status":String,
	   "date":Date
	},
	"other":{
	   "status":String,
	   "date":Date
	},

	

	"date":Date,
	"maturaty_of_baby_weeks":Number,
	"baby's_growth":{
	   "SGA":Boolean,
	   "AGA":Boolean,
	   "LGA":Boolean
	},
	"blood_group_of_baby":String,
	"peripheries_pink_and_warm":{
	   "noraml":String,
	   "abnormal":String
	},
	"hydration":{
	  "status":String,
	   "date":Date
	},
	"response_to_hnadling":{
	  "status":String,
	   "date":Date
	},
	"capillary_refilling_time":{
	  "status":String,
	   "date":Date
	},
	"pulse_rate_or_volume":{
	  "status":String,
	   "date":Date
	},
	"heart_murmurs":{
	  "status":String,
	   "date":Date
	},
	"femoral_pulse":{
	  "status":String,
	   "date":Date
	},
	"respiratory_rate":{
	  "status":String,
	   "date":Date
	},
	"grunting":{
	  "status":String,
	   "date":Date
	},
	"intercostal_or_subcostal_recession":{
	  "status":String,
	   "date":Date
	},
	"tone":{
	   "status":String,
	   "date":Date
	},
	"OFC":{
	  "status":String,
	   "date":Date
	},
	"fontamelle_or_suture_line":{
	  "status":String,
	   "date":Date
	},
	"eyes_or_red_reflex":{
	  "status":String,
	   "date":Date
	},
	"scalp":{
	  "status":String,
	   "date":Date
	},
	"mouth_lips":{
	  "status":String,
	   "date":Date
	},
	"palate":{
	  "status":String,
	   "date":Date
	},
	"ears":{
	   "status":String,
	   "date":Date
	},
	"abdomen":{
	   "status":String,
	   "date":Date
	},
	"umbilicus":{
	  "status":String,
	   "date":Date
	},
	"genitalia":{
	  "status":String,
	   "date":Date
	},
	"anus":{
	  "status":String,
	   "date":Date
	},
	"hips":{
	  "status":String,
	   "date":Date
	},
	"spine":{
	  "status":String,
	   "date":Date
	},
	"limbs":{
	  "status":String,
	   "date":Date
	},
	"dysmorphic_featurse":{
	  "status":String,
	   "date":Date
	},
	"superficial_infection_skin":{
	  "status":String,
	   "date":Date
	},
	"birth_injuries":{
	  "status":String,
	   "date":Date
	},
	"other_abnomalities":String,
	"action_taken":{
	   "transfered_for_special_care":String,
	   "discharged":String

	},
	"diagnosis_of_discharge":String,
	"date_of_discharge":String,

	

   "color_of_skin":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	},
	"eyes":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	},
	"the_native_of_lobbyists":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	},
	"tempreture":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	},
	"only_breastfeeding":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	},
	"breastfeeding":{
	"sthapithya":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	},
	"connection":{
	"ten_days_from_birth":{
	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
	}
	},
	"other":{
	"ten_days_from_birth":{

	  "one_five_days":{
          "date":Date,
          "status":String
	  },
	  "six_ten_days":{
	        "date":Date,
          "status":String

	  }
	},
	"fourteen_twentytwo_days":{
	     "date":Date,
          "status":String
	},
	"fourtytwo_days":{
	   "date":Date,
          "status":String
	}
    },
    
    "first_month_from_birth":{
        "does_child's_eyes_toward_the_light":Boolean,
        "does_the_child_look_good_on_your_face":Boolean
   
       },
       "in_second_month":{
       "when_you_turn_your_face_to_the_side_do_you_see_the_child_smiling_in_response":Boolean,
        "then_the_baby's_eyes_move":Boolean
       },
       "in_sixth_month":{
       "does_the_child_look_arround":Boolean,
       "is_child_streching_out_his_hand_and_tryimg_to_touch_something":Boolean,
       "do_you_suspect_that_your_child_has_a_problem":Boolean
       },
       "in_tenth_month":{
       "is_it_possible_for_a_child_to_pickup_small_things_with_a_thumb_and_forefinger":Boolean
       },
       "in_tweleth_month":{
       "have_your_child_strech_out_his_hand_and_touch_them":Boolean,
       "if_the_person_identifies_them_the_child_will_recognize_them_before_they_call_them":Boolean
       },
       "in_the_few_moments_after_the_birth":{
       "if_your_child_is_startled_by_a_sudden_loud_noise_does_his_stutter_or_widden_his_eyes":Boolean
       },
       "in_first_month":{
       "does_your_child_detect_sudden_or_presistent_noises_and_begin_to_listen_quitely_to_eve":Boolean
       },
       "from_four_month":{
       "if_they_can't_see_their_mother_do_they_keep_silent_or_laugh_when_their_voice_is_heard":Boolean,
       "when_the_mother_speaks_from_the_side_or)from_the_back_does_child_turn_his_head_or_eyes":Boolean
       },
       "from_seven_month":{
       "does_child_turn_to_the_mother_side_immediately_after_speaking":Boolean
       },
       "from_nine_month":{
       "listen_to_the_familiar_sounds_does_child_hear_everyday":Boolean,
       "does_find_out_about_noises_from_an_unknown_location":Boolean,
       "does_child_like_it_when_talking_to_a_loud_tune":Boolean
       },
       "when_twelve_month":{
       "does_he_respond_to_other_familiar_sounds_nd_his_name":Boolean,
       "does_he_respond_to_words_even_when_they_do_not":Boolean
       },
    
       "from_six_months_to_three_months":{
       "lie_on_his_hips_and_head_up":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "something_keeps_moving_from_one_place_to_another":{
        "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "stopping_or_increasing_action_responds_to_a_sudden_loud_noise":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "sounds_like_a_e_in_response_to_stimulus":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "the_mother_recognize_and_smiles":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },
       "from_three_to_six_months":{
       "raise_the_head_chest_while_standing_up":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "they_play_when_crossing_fingers":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "streching_his_hands_toward_something_he_hold_it_with_his_whole_hand":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "when_heard_a_sound_he_turn_his_head_toward_that":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "emits_single_letter_sounds":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "smiles_loudely":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },
       "from_six_to_nine_months":{
       "lie_your_hips_and_head_up":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "turn_back_again_and_again":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "change_something_another_hand_to_other_hand":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "some_sounds_are_repeated":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },
       "from_nine_to_twelve_month":{
       "siting_withou_help":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "holding_himself_alone":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "holding_small_things_using_thumb_And_forefinger":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "following_voice":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "pronounce_individual_words_makes_sounds_that_make_sense":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "understand_simple_instructions":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },
       "from_twelve_to_eighteen":{
       "walking_with_help":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "they_can_speak_At_least_two_or_three_words":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "hand_is_pointed_out_when_hearing_familiar_things":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "they_can_roll_a_boll":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "can_identify_at_least_one_body_part":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },
       "from_eghiteen_month_to_two_years":{
       "walking_without_help":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "can_climb_the_stair_with_help":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "can_make_a_tower_using_building_blocks":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "eat_himself_alone":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "can_talk_about_ten_words_can_talk_at_least_one_sentence_with_two_words":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "the_lips_are_sharpened_to_kiss":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },
       "from_two_to_three_years":{
       "ability_to_run_without_falling":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "ability_to_down_and_up_stair":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "can_copy_an_art_with_a_circle":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       },
       "can_create_a_sentence_with_three_or_more_words":{
       "age_at_the_time_of_occurence":Number,
       "age_at_the_confirmed":Number,
       "status_of_the_officer":String
       }
       },

       "age_of_child":{
           "one_month":{
               "date_of_clinics":Date,
               "squint":String,
               "cataract":String,
               "impairment_of_eye_movement":String,
               "hearing":{
                   "left":Boolean,
                   "right":Boolean
               },
               "development":{
                   "weight":Number,
                   "height":Number
               },
               "heart_disease":String,
               "lungs":String,
               "hip_joint":String,
               "inheited_problems":String,
               "other_diseases":String,
               "designation_of_officer":String
           },
           "two_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "three_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "four_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "six_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "nine_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "twelve_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "eighteen_month":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "three_years":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "night_blindness":String,
            "bito_spots":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "four_years":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "night_blindness":String,
            "bito_spots":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },
        "five_years":{
            "date_of_clinics":Date,
            "squint":String,
            "cataract":String,
            "impairment_of_eye_movement":String,
            "sight":{
                "left":Boolean,
                "right":Boolean
            },
            "night_blindness":String,
            "bito_spots":String,
            "hearing":{
                "left":Boolean,
                "right":Boolean
            },
            "dental_caries":{
                "white_brown_spots":String,
                "dental_cavities":String
            },
            "development":{
                "weight":Number,
                "height":Number
            },
            "heart_disease":String,
            "lungs":String,
            "hip_joint":String,
            "inheited_problems":String,
            "other_diseases":String,
            "designation_of_officer":String
        },

       },
       
       "date_of_checked":Date,
       "special_notice":String,
   
   
   
       "age_of_child":{
       "six":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "seven":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "eight":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "nine":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "ten":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "eleven":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "twelve":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "thirteen":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "fourteen":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "fifteen":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "sixteen":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "seventeen":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       },
       "eighteen":{
          "Number_of_teeth":Number,
          "status":String,
          "date":Date
       }
       },
    
       
   
       
   
       "at_birth":{
       "b_c_g":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String,
       "b_c_g_scar":Boolean
       },
       "b_c_g_second_dose":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "two_months_completed":{
       "pentavalent_one":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       },
       "opv_one":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "four_months_completed":{
       "pentavalent":{
       "Date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       },
       "opv_two":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "nine_months_completed":{
       "live_je":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "twelve_months_completed":{
       "measules_mumps_rubella":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "eighteen_month_completed":{
       "dpt":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       },
       "opv_four":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "three_year_completed":{
       "measules_rubella_two":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "five_year_completed":{
       "d_t":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       },
       "opv_five":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "twelve_year_completed":{
       "adult_tatanus_diphtheria":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
       "other":{
       "details":{
       "date":{
       "year":Number,
       "month":Number,
       "day":Number
       },
       "batch_no":String,
       "effects_of_immunization":String
       }
       },
   
       
   
       "date_of_refferals":Date,
       "reason_for_referrals":String,
       "place_of_refferal":String,
       "notes_on_back":String,
   
       "A_vitamine":{
       "six_month":{
       "date":Date,
       "batch_no":String
       },
       "one_year":{
       "date":Date,
       "batch_no":String
       },
       "one_half_year":{
       "date":Date,
       "batch_no":String
       },
       "two_year":{
       "date":Date,
       "batch_no":String
       },
       "two_half_year":{
       "date":Date,
       "batch_no":String
       },
       "three_year":{
       "date":Date,
       "batch_no":String
       },
       "three_half_year":{
       "date":Date,
       "batch_no":String
       },
       "four_year":{
       "date":Date,
       "batch_no":String
       },
       "four_half_year":{
       "date":Date,
       "batch_no":String
       },
       "five_year":{
       "date":Date,
       "batch_no":String
       }
   
       },
   
       "warm_treat":{
       
       "one_year":{
       "date":Date,
       "batch_no":String
       },
       "one_half_year":{
       "date":Date,
       "batch_no":String
       },
       "two_year":{
       "date":Date,
       "batch_no":String
       },
       "two_half_year":{
       "date":Date,
       "batch_no":String
       },
       "three_year":{
       "date":Date,
       "batch_no":String
       },
       "three_half_year":{
       "date":Date,
       "batch_no":String
       },
       "four_year":{
       "date":Date,
       "batch_no":String
       },
       "four_half_year":{
       "date":Date,
       "batch_no":String
       },
       "five_year":{
       "date":Date,
       "batch_no":String
       }
   
       },
})